-- =============================================================================
-- AUTHORITATIVE SCHEMA BASELINE — captured from the LIVE production database
-- Project: adtlnvihwrcqcasqcjwd  (andrewsdetail.com)
-- =============================================================================
-- This file reflects the ACTUAL structure of the live database as of this
-- capture. It is the single source of truth for the schema. The older, partial
-- migration files in this folder were hand-written over time and drifted from
-- production; treat THIS file as the real baseline.
--
-- NOTE: This is a documentation/rebuild baseline. It is NOT meant to be run
-- against the live database (the tables already exist). Use it to understand the
-- schema and to stand up a fresh/dev database. Incremental changes should be
-- added as new, later-dated migration files after this one.
--
-- RLS is currently DISABLED on all tables in production (see docs/ARCHITECTURE.md
-- §8 and docs/TODO.md). Enabling it is a separate, coordinated change.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- packages — the services offered (interior/exterior × standard/deluxe/ultimate)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.packages (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name             varchar NOT NULL,
    category         varchar NOT NULL CHECK (category IN ('interior', 'exterior')),
    tier             varchar NOT NULL CHECK (tier IN ('standard', 'deluxe', 'ultimate')),
    base_price       numeric NOT NULL,
    duration_minutes integer NOT NULL,
    description      text,
    is_active        boolean DEFAULT true,
    created_at       timestamptz DEFAULT timezone('utc', now()),
    updated_at       timestamptz DEFAULT timezone('utc', now())
);

-- ---------------------------------------------------------------------------
-- customers — one row per person (NOTE: id is BIGINT, not uuid)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.customers (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   text NOT NULL,
    email                  text,
    phone                  text NOT NULL,
    address                text,
    notes                  text,
    referral_code          text UNIQUE,
    completed_washes_count integer DEFAULT 0,
    loyalty_reward_eligible boolean DEFAULT false,
    created_at             timestamptz DEFAULT now(),
    updated_at             timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- admin_users — who may log into /admin (id links to auth.users)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admin_users (
    id         uuid PRIMARY KEY,
    email      text NOT NULL UNIQUE,
    role       text DEFAULT 'admin',
    is_active  boolean DEFAULT true,
    created_at timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- add_ons — extra services / discounts
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.add_ons (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name             text NOT NULL,
    description      text,
    price            numeric NOT NULL,
    type             text NOT NULL CHECK (type IN ('interior', 'exterior')),
    duration_minutes integer DEFAULT 0,
    discount_type    text NOT NULL DEFAULT 'amount' CHECK (discount_type IN ('amount', 'percentage')),
    value            numeric,
    is_active        boolean DEFAULT true,
    created_at       timestamptz DEFAULT now(),
    updated_at       timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- bookings — the heart of the app
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bookings (
    id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Customer (denormalized snapshot on the booking)
    customer_name            varchar NOT NULL,
    customer_phone           varchar NOT NULL,
    customer_email           varchar NOT NULL,
    customer_address         text,
    -- Schedule
    booking_date             date NOT NULL,
    start_time               time NOT NULL,
    end_time                 time NOT NULL,
    total_duration_minutes   integer NOT NULL,
    -- Service
    service_type             varchar NOT NULL CHECK (service_type IN ('mobile', 'dropoff')),
    vehicle_size             varchar NOT NULL CHECK (vehicle_size IN ('small', 'medium', 'large')),
    vehicle_size_fee         numeric NOT NULL DEFAULT 0,
    vehicle_model            text,
    interior_package_id      uuid REFERENCES public.packages(id),
    exterior_package_id      uuid REFERENCES public.packages(id),
    has_water_electric       boolean DEFAULT false,
    customer_notes           text,
    -- Pricing
    subtotal                 numeric NOT NULL,
    total_price              numeric NOT NULL,
    applied_promo_code       varchar,
    promo_discount           numeric,
    monthly_plan_id          integer,
    monthly_plan_name        text,
    monthly_plan_discount    numeric,
    -- Payment finalization
    final_amount             numeric,
    payment_status           text DEFAULT 'pending',
    line_items               jsonb,   -- being migrated to a structured table (see TODO)
    payment_notes            text,
    finalized_at             timestamptz,
    -- Integrations & status
    google_calendar_event_id varchar,
    ics_file_sent            boolean DEFAULT false,
    status                   varchar DEFAULT 'confirmed'
                                 CHECK (status IN ('confirmed', 'cancelled', 'completed', 'no_show')),
    created_at               timestamptz DEFAULT timezone('utc', now()),
    updated_at               timestamptz DEFAULT timezone('utc', now())
);

-- ---------------------------------------------------------------------------
-- booking_add_ons — add-ons attached to a booking
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.booking_add_ons (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id uuid REFERENCES public.bookings(id),
    add_on_id  uuid REFERENCES public.add_ons(id),
    quantity   integer DEFAULT 1,
    notes      text,
    created_at timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- blockout_dates — unavailable days/times
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.blockout_dates (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    event_name text NOT NULL,
    start_date date NOT NULL,
    end_date   date NOT NULL,
    all_day    boolean NOT NULL DEFAULT false,
    start_time time,
    end_time   time,
    repeat     text DEFAULT 'none',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- booking_hours_overrides — custom open/close hours for specific dates
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.booking_hours_overrides (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date       date NOT NULL UNIQUE,
    open_time  time NOT NULL,
    close_time time NOT NULL,
    notes      text
);

-- ---------------------------------------------------------------------------
-- dropoff_only_periods — windows offering drop-off only (no mobile)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dropoff_only_periods (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date date NOT NULL,
    end_date   date,
    start_time time,
    end_time   time,
    reason     text,
    created_at timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- expenses — business expenses
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.expenses (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date           date NOT NULL,
    category       text NOT NULL,
    description    text NOT NULL,
    amount         numeric NOT NULL,
    payment_method text NOT NULL,
    notes          text,
    created_at     timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- promo_codes — discount codes
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.promo_codes (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    code        text NOT NULL UNIQUE,
    type        text NOT NULL CHECK (type IN ('percentage', 'amount')),
    value       numeric NOT NULL CHECK (value > 0),
    expires_at  timestamptz,
    usage_limit integer,
    times_used  integer DEFAULT 0,
    is_active   boolean DEFAULT true,
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- monthly_plans — subscription/membership discount plans
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.monthly_plans (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           text NOT NULL,
    description    text,
    discount_type  text NOT NULL DEFAULT 'amount' CHECK (discount_type IN ('percentage', 'amount')),
    discount_value numeric NOT NULL DEFAULT 0,
    is_active      boolean DEFAULT true,
    created_at     timestamptz DEFAULT now(),
    updated_at     timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- referrals — referral tracking (currently unused/empty)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.referrals (
    id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    referrer_code        text REFERENCES public.customers(referral_code),
    referred_customer_id bigint REFERENCES public.customers(id),
    booking_id           uuid REFERENCES public.bookings(id),
    benefit_applied      boolean DEFAULT false,
    created_at           timestamp DEFAULT now()
);
